In [1]:
import numpy as np

In [3]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [4]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
z.shape

(10,)

In [8]:
z.shape = (10, 1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [9]:
type(z[0])

numpy.ndarray

In [10]:
z = np.empty(3)
z

array([0., 0., 0.])

In [12]:
z = np.linspace(2, 10, 5)
z

array([ 2.,  4.,  6.,  8., 10.])

In [13]:
a_list = [1, 2, 3, 4, 5, 6, 7]
z = np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7]])

In [14]:
b_list = [9, 8, 7, 6, 5, 4, 3], [1, 2, 3, 4, 5, 6, 7]
z = np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [15]:
z.shape
?z.shape

In [18]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [19]:
x1[0]

5

In [20]:
x1[0:2]

array([5, 0])

In [21]:
x1[-1]

9

In [25]:
from skimage import io
photo = io.imread('york_minister.jpg')
type(photo)

FileNotFoundError: No such file: 'C:\Users\USER\york_minister.jpg'